# Generated by Django 4.2.24 on 2025-09-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=100)),
                ('title', models.CharField(default='Frontend Developer', max_length=100)),
                ('bio', models.TextField(default='I have high level experience in web design, development knowledge and producing quality work')),
                ('home_image', models.URLField(blank=True, default='https://i.postimg.cc/3NgvPcZD/home-img.png')),
                ('about_image', models.URLField(blank=True, default='https://i.postimg.cc/W1YZxTpJ/about-img.jpg')),
                ('about_heading', models.CharField(default="Hi, I'm Your Name, based in Your Location", max_length=200)),
                ('about_description', models.TextField(default="I'm a web developer, with extensive knowledge and years of experience, working with quality work in web technologies, UI and UX design")),
                ('years_experience', models.CharField(default='10 +', max_length=20)),
                ('projects_completed', models.CharField(default='60 +', max_length=20)),
                ('support_availability', models.CharField(default='Online 24/7', max_length=20)),
                ('email', models.EmailField(default='user@gmail.com', max_length=254)),
                ('phone', models.CharField(default='999-888-777', max_length=20)),
                ('messenger', models.CharField(default='user.fb123', max_length=50)),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com')),
                ('twitter_url', models.URLField(blank=True, default='https://www.x.com')),
                ('resume_url', models.URLField(blank=True, help_text='Link to your resume/CV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
