# Generated by Django 4.2 on 2025-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='home_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]

