[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn config.wsgi --chdir backend --preload --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/health/"
healthcheckTimeout = 300
restartPolicyType = "never"

[env]
PYTHONUNBUFFERED = "1"
DJANGO_SETTINGS_MODULE = "config.settings"
PORT = "8000"
